version: "3.8"

services:
  web:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    command: bash -c "python manage.py migrate && gunicorn tutorialproject.wsgi -b 0.0.0.0:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
