version: "3.8"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build:
      context: ./api
    ports:
      - 8000:8000
    volumes:
      - .:/api
    command: bash -c "python manage.py migrate \
      && python manage.py collectstatic --no-input \
      && gunicorn todoproject.asgi:application -b 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
      - SECRET_KEY=zm7vfcy=w^rg2oyi&#@^vuqc)yl^#6vun4bzs1j*ew&(%#0iaq
    depends_on:
     - db
